package BenchFarm::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'BenchFarm::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=robe;host=localhost;user=robe',
        user => '',
        password => '',
    }
);

=head1 NAME

BenchFarm::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<BenchFarm>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<BenchFarm::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

robe

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
